#!/bin/bash

echo "============================================="
echo "Yaci DevKit + Hydra Local Devnet Help (NPM Setup)"
echo "============================================="
echo ""
echo "NPM Distribution Quick Start:"
echo "---------------------------------------------"
echo "1. Install Yaci DevKit (if not already):"
echo "   npm i -g @bloxbean/yaci-devkit"
echo ""
echo "2. (Optional) Install Yaci Viewer:"
echo "   npm install -g @bloxbean/yaci-viewer"
echo ""
echo "3. Start the devnet:"
echo "   yaci-devkit up --enable-yaci-store --interactive"
echo "   # For sub-second block time:"
echo "   yaci-devkit up --enable-yaci-store --block-time 0.1 --slot-length 0.1 --epoch-length 80"
echo ""
echo "4. In another terminal, start the Yaci Viewer:"
echo "   yaci-viewer"
echo ""
echo "5. Fund test addresses (in the interactive CLI):"
echo "   devnet:default> topup <address> <amount>"
echo ""
echo "6. To stop the devnet:"
echo "   devnet:default> stop"
echo "   # Or in a separate terminal:"
echo "   yaci-devkit stop"
echo ""
echo "7. To reset the devnet:"
echo "   devnet:default> reset"
echo ""
echo "Service URLs (default):"
echo "  Cardano Node:         http://localhost:3001"
echo "  Yaci Store (API):     http://localhost:8080"
echo "  Yaci Viewer:          http://localhost:5173"
echo "  Ogmios (if enabled):  ws://localhost:1337"
echo "  Kupo (if enabled):    http://localhost:1442"
echo ""
echo "For more commands and troubleshooting, see the documentation:"
echo "  https://kushal2060.github.io/hydra-yaci/"
echo "  https://devkit.yaci.xyz/"
echo "============================================="
echo ""